import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { syncRepository } from '../scripts/sync.mjs';

function git(cwd, ...args) {
  const result = spawnSync('git', args, { cwd, encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return result.stdout.trim();
}

function fixture(t, { failingCheck = false } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'liquidglass-sync-'));
  t.after(() => {
    assert.equal(dirname(resolve(dir)), resolve(tmpdir()));
    assert(dir.includes('liquidglass-sync-'));
    rmSync(dir, { recursive: true, force: true });
  });
  const root = join(dir, 'work');
  const remote = join(dir, 'remote.git');
  mkdirSync(root);
  git(dir, 'init', '--bare', remote);
  git(root, 'init', '-b', 'main');
  git(root, 'config', 'user.name', 'Sync Test');
  git(root, 'config', 'user.email', 'sync-test@example.invalid');
  git(root, 'config', 'commit.gpgsign', 'false');
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'sync-fixture', private: true, scripts: { check: 'node check.cjs' } }));
  writeFileSync(join(root, '.gitignore'), '.check-ran\n');
  writeFileSync(join(root, 'check.cjs'), `const fs = require('node:fs'); fs.writeFileSync('.check-ran', 'yes'); ${failingCheck ? 'process.exit(1);' : "fs.copyFileSync('source.txt', 'artifact.txt');"}`);
  writeFileSync(join(root, 'source.txt'), 'before\n');
  writeFileSync(join(root, 'artifact.txt'), 'before\n');
  git(root, 'add', '.');
  git(root, 'commit', '-m', 'fixture baseline');
  git(root, 'remote', 'add', 'origin', remote);
  git(root, 'push', '-u', 'origin', 'main');
  const baseline = git(root, 'rev-parse', 'HEAD');
  writeFileSync(join(root, 'source.txt'), 'after\n');
  return {
    root, remote, baseline,
    options: { root, expectedOrigin: remote, confirmed: true, message: 'fix: confirmed repair', files: ['source.txt', 'artifact.txt'] },
  };
}

test('sync requires confirmation and leaves Git untouched without it', t => {
  const f = fixture(t);
  assert.throws(() => syncRepository({ ...f.options, confirmed: false }), /User confirmation/);
  assert.equal(git(f.root, 'rev-parse', 'HEAD'), f.baseline);
  assert.equal(git(f.remote, 'rev-parse', 'refs/heads/main'), f.baseline);
  assert.equal(existsSync(join(f.root, '.check-ran')), false);
});

test('failed checks cannot stage, commit or push a repair', t => {
  const f = fixture(t, { failingCheck: true });
  assert.throws(() => syncRepository(f.options), /failed/);
  assert.equal(existsSync(join(f.root, '.check-ran')), true);
  assert.equal(git(f.root, 'diff', '--cached', '--name-only'), '');
  assert.equal(git(f.root, 'rev-parse', 'HEAD'), f.baseline);
  assert.equal(git(f.remote, 'rev-parse', 'refs/heads/main'), f.baseline);
});

test('existing staged changes are preserved and stop sync before checking', t => {
  const f = fixture(t);
  git(f.root, 'add', 'source.txt');
  const stagedBefore = git(f.root, 'diff', '--cached');
  assert.throws(() => syncRepository(f.options), /already contains staged/);
  assert.equal(git(f.root, 'diff', '--cached'), stagedBefore);
  assert.equal(existsSync(join(f.root, '.check-ran')), false);
  assert.equal(git(f.remote, 'rev-parse', 'refs/heads/main'), f.baseline);
});

test('unreviewed changes and omitted build output prevent a partial commit', t => {
  const f = fixture(t);
  writeFileSync(join(f.root, 'unrelated.txt'), 'keep me');
  assert.throws(() => syncRepository(f.options), /outside the reviewed file list: unrelated.txt/);
  assert.equal(existsSync(join(f.root, '.check-ran')), false);
  // Include the unrelated file explicitly, but omit the output generated by checks.
  assert.throws(() => syncRepository({ ...f.options, files: ['source.txt', 'unrelated.txt'] }), /outside the reviewed file list: artifact.txt/);
  assert.equal(readFileSync(join(f.root, 'unrelated.txt'), 'utf8'), 'keep me');
  assert.equal(git(f.root, 'diff', '--cached', '--name-only'), '');
  assert.equal(git(f.root, 'rev-parse', 'HEAD'), f.baseline);
});

test('a newer remote is detected without rebasing or overwriting local changes', t => {
  const f = fixture(t);
  const other = join(dirname(f.root), 'other');
  git(dirname(f.root), 'clone', '--branch', 'main', f.remote, other);
  git(other, 'config', 'user.name', 'Other Test');
  git(other, 'config', 'user.email', 'other-test@example.invalid');
  git(other, 'config', 'commit.gpgsign', 'false');
  writeFileSync(join(other, 'other.txt'), 'remote update');
  git(other, 'add', 'other.txt');
  git(other, 'commit', '-m', 'concurrent update');
  git(other, 'push', 'origin', 'main');
  const remoteHead = git(f.remote, 'rev-parse', 'refs/heads/main');
  assert.throws(() => syncRepository(f.options), /differs from GitHub main/);
  assert.equal(git(f.root, 'rev-parse', 'HEAD'), f.baseline);
  assert.equal(git(f.remote, 'rev-parse', 'refs/heads/main'), remoteHead);
  assert.equal(readFileSync(join(f.root, 'source.txt'), 'utf8'), 'after\n');
  assert.equal(existsSync(join(f.root, '.check-ran')), false);
});

test('confirmed sync checks, commits source plus rebuilt output, and verifies the push', t => {
  const f = fixture(t);
  const result = syncRepository(f.options);
  assert.equal(result.status, 'pushed');
  assert.notEqual(result.sha, f.baseline);
  assert.equal(git(f.remote, 'rev-parse', 'refs/heads/main'), result.sha);
  assert.equal(git(f.remote, 'show', 'main:artifact.txt'), 'after');
  assert.equal(git(f.root, 'show', '--format=', '--name-only', 'HEAD'), 'artifact.txt\nsource.txt');
  assert.equal(git(f.root, 'status', '--porcelain'), '');
  const again = syncRepository(f.options);
  assert.deepEqual(again, { status: 'unchanged', sha: result.sha });
});

test('a rejected push keeps the local commit and never claims remote success', t => {
  const f = fixture(t);
  writeFileSync(join(f.remote, 'hooks', 'pre-receive'), '#!/bin/sh\nexit 1\n', { mode: 0o755 });
  assert.throws(() => syncRepository(f.options), /saved locally.*Push is not verified/);
  assert.notEqual(git(f.root, 'rev-parse', 'HEAD'), f.baseline);
  assert.equal(git(f.remote, 'rev-parse', 'refs/heads/main'), f.baseline);
  assert.equal(git(f.root, 'status', '--porcelain'), '');
});
